import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const between=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
const source=between('      function showAdminAuthOverlay(', '      async function fetchWithTimeout')+between('      let adminSessionVerifiedAt','      async function startAdminAuth')+
 between('      async function validateExistingAdminSession','      function switchAdminTab');
function fixture(){
 let reads=0,checks=0,navigations=0,reloads=0;
 const events={},storage=new Map([['token','fixture']]);
 const nodes=Object.fromEntries(['adminAuthOverlay','adminAuthMessage','adminAuthRetryBtn','adminAuthRefreshBtn','adminAuthCloseBtn'].map(id=>{const classes=new Set();return [id,{dataset:{},innerText:'',classList:{toggle:(name,hidden)=>hidden?classes.add(name):classes.delete(name),add:name=>classes.add(name),remove:name=>classes.delete(name),contains:name=>classes.has(name)}}]}));
 const node=nodes.adminAuthRetryBtn;
 const c={Date,URLSearchParams,ADMIN_LINE_SESSION_TOKEN_KEY:'token',ADMIN_LINE_STATE_KEY:'state',ADMIN_AUTH_TIMEOUT_MS:60000,GAS_ORDERS_API_URL:'mock',adminAuthBlocksDataLoad:false,
 shouldOfferAdminRefreshFromMessage:()=>false,document:{visibilityState:'visible',getElementById:id=>nodes[id],addEventListener:(n,f)=>events[n]=f},window:{location:{search:'',reload:()=>{reloads++}},addEventListener:(n,f)=>events[n]=f},sessionStorage:{getItem:k=>storage.get(k)||null,removeItem:k=>storage.delete(k)},setAdminAuthRetryButtonMode(){},createAdminDiagnosticRequestId:()=> 'fixture',publishAdminAuthDiagnostic(){},reconcilePendingAdminShipment:async()=>{reads++},startAdminAuth:async()=>{navigations++},fetchAdminRecoverableResponse:async()=>{checks++;return {ok:true,json:async()=>({ok:true,action:'adminValidateSession',allowed:true})}}};
 vm.createContext(c);vm.runInContext(source,c);
 return {c,events,storage,node,nodes,stats:()=>({checks,reads,navigations,reloads})};
}
let f=fixture();assert.equal(await f.c.initAdminAuth({validateWithOrders:true}),true);assert.equal(f.stats().checks,0,'initial protected order read performs validation; no redundant login request');assert.equal(f.nodes.adminAuthOverlay.classList.contains('hidden'),false,'no usable UI until authenticated data arrives');
f=fixture();vm.runInContext('adminInitialOrdersReady=true',f.c);f.c.markAdminSessionVerified();assert.equal(await f.c.ensureAdminSessionReady(),true);assert.equal(f.stats().checks,0);
f.c.initializeAdminSessionRecovery();f.c.document.visibilityState='hidden';f.events.visibilitychange();assert.equal(f.stats().checks,0);f.c.document.visibilityState='visible';f.events.visibilitychange();await new Promise(setImmediate);assert.equal(f.stats().checks,1);assert.equal(f.stats().reads,1);assert.equal(f.nodes.adminAuthOverlay.classList.contains('hidden'),true);
f=fixture();let finish;f.c.fetchAdminRecoverableResponse=()=>new Promise(r=>finish=r);const one=f.c.ensureAdminSessionReady(true),two=f.c.ensureAdminSessionReady(true);assert.equal(f.c.adminAuthBlocksDataLoad,true);assert.equal(f.node.classList.contains('hidden'),true,'do not offer LINE navigation during a pending session check');assert.match(f.nodes.adminAuthMessage.innerText,/正在確認/);finish({ok:true,json:async()=>({ok:true,allowed:true,action:'adminValidateSession'})});assert.equal(await one,true);assert.equal(await two,true);
f=fixture();f.c.fetchAdminRecoverableResponse=async()=>({ok:true,json:async()=>({ok:false,action:'adminValidateSession',error:'ADMIN_SESSION_REQUIRED'})});assert.equal(await f.c.ensureAdminSessionReady(true),false);assert.equal(f.storage.has('token'),false);assert.match(f.nodes.adminAuthMessage.innerText,/登入已過期/);assert.equal(f.stats().navigations,0,'resuming an expired form must not automatically navigate away and discard draft');assert.equal(f.c.adminAuthBlocksDataLoad,true);
f=fixture();f.c.fetchAdminRecoverableResponse=async()=>{throw Error('NETWORK_ERROR')};assert.equal(await f.c.ensureAdminSessionReady(true),false);assert.equal(f.storage.get('token'),'fixture');assert.equal(f.node.dataset.retrySession,'true');
f=fixture();vm.runInContext('adminInitialOrdersReady=true',f.c);f.c.fetchAdminRecoverableResponse=async()=>{throw Error('NETWORK_ERROR')};await f.c.ensureAdminSessionReady(true);assert.equal(f.node.dataset.retrySession,'true');
f.c.showAdminAuthOverlay('讀取訂單中',false);assert.match(f.nodes.adminAuthMessage.innerText,/暫時無法確認/,'ordinary loading must not overwrite a blocked authentication failure');
f.c.fetchAdminRecoverableResponse=()=>new Promise(r=>finish=r);const retry=f.c.retryAdminSessionFromOverlay();assert.equal(f.node.disabled,true);assert.equal(f.node.classList.contains('hidden'),true);assert.equal(f.stats().reloads,0);finish({ok:true,json:async()=>({ok:true,allowed:true,action:'adminValidateSession'})});await retry;assert.equal(f.stats().reloads,0,'resuming retry preserves the current page and unsaved draft');assert.equal(f.stats().reads,1,'only reconcile pending results; no order reload or mutation');assert.equal(f.node.disabled,false);assert.equal(f.nodes.adminAuthOverlay.classList.contains('hidden'),true);
f.c.fetchAdminRecoverableResponse=async()=>{throw Error('NETWORK_ERROR')};await f.c.retryAdminSessionFromOverlay();assert.equal(f.node.disabled,false);assert.equal(f.node.classList.contains('hidden'),false);assert.equal(f.storage.get('token'),'fixture');assert.equal(f.stats().reloads,0);
f=fixture();await f.c.retryAdminSessionFromOverlay();assert.equal(f.stats().reloads,1,'initial failed bootstrap still follows the existing initialization path');
console.log('session resume: PASS initial request elimination, protected UI, hidden/resume, single flight, expired draft retention, network distinction');
