import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
function fn(name){const start=html.indexOf(`      function ${name}(`);assert(start>=0,name);return html.slice(start,html.indexOf('\n      function ',start+1));}
const product=(id,series,count=6,extra={})=>({id,code:id,variety:'蔗香梨',grade:'22A',count:`${count}顆`,price:1200,productSeries:series,category:'一般禮盒',status:'上架',...extra});
const products=[product('G6',''),product('P6','精裝版'),product('P8','精裝版',8),product('M6','',6,{variety:'牛奶梨'}),product('G122','',6,{grade:'122A'})];
const c={adminProductCatalog:products,normalizeAdminProductCode:x=>String(x||'').replace(/\s/g,'').toUpperCase(),escapeHtml:x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),getShippingManifestOrderPackageSpecs:()=>['3']};vm.createContext(c);
vm.runInContext(['parseShippingManifestItems','buildShippingManifestStats','getShippingManifestProductId','getShippingManifestProductDisplayLabel','buildShippingManifestProductSummary'].map(fn).join('\n'),c);
assert.equal(c.getShippingManifestProductId('蔗香梨 精裝版 22A｜6顆',1200),'P6','explicit premium must not resolve as same-price gift');
assert.equal(c.getShippingManifestProductId('蔗香梨 禮盒版 22A｜6顆',1200),'G6');
assert.equal(c.getShippingManifestProductId('蔗香梨 精裝版 22A｜8顆',1200),'P8');
assert.equal(c.getShippingManifestProductId('牛奶梨 禮盒版 22A｜6顆',1200),'M6');
assert.equal(c.getShippingManifestProductId('蔗香梨 禮盒版 122A｜6顆',1200),'G122');
assert.equal(c.getShippingManifestProductId('蔗香梨 精裝版 22A｜10顆',1200),'','must not guess count');
assert.equal(c.getShippingManifestProductId('蔗香梨 精裝版 24A｜6顆',1200),'','must not guess grade');
assert.equal(c.getShippingManifestProductId('蔗香梨 22A｜6顆',1200),'','ambiguous historical packaging requires review');
assert.equal(c.getShippingManifestProductId('P6',1200),'P6','exact SKU identity wins');
assert.equal(c.getShippingManifestProductId('蔗香梨 精裝版 22A｜6顆',1100),'P6','historical price changes must not override explicit variant');
const orders=[{itemsSummary:'蔗香梨 禮盒版 22A｜6顆（$1200 × 2盒）\n蔗香梨 精裝版 22A｜6顆（$1200 × 3盒）\n蔗香梨 精裝版 22A｜8顆（$1200 × 1盒）',totalBoxes:6,finalAmount:7200}];
const stats=c.buildShippingManifestStats(orders),summary=c.buildShippingManifestProductSummary(stats);
assert.equal(stats.boxTotal,6);assert.equal(stats.productTotals.size,3);
for(const label of ['22A｜禮盒版｜6顆：2 盒','22A｜精裝版｜6顆：3 盒','22A｜精裝版｜8顆：1 盒'])assert(summary.includes(label),label);
assert(!summary.includes('6顆：5 盒'));assert(summary.includes('合計：6 盒'));
c.adminProductCatalog=[product('old','',8,{status:'停售',grade:'18A'}),product('current','',8,{grade:'18A'})];
assert.equal(c.getShippingManifestProductId('蔗香梨 18A',1200),'current','equivalent legacy duplicate remains supported');
c.adminProductCatalog=[product('gift','',6),product('premium','精裝版',6,{price:1300})];
assert.equal(c.getShippingManifestProductId('蔗香梨 22A｜6顆',1200),'gift','legacy price can resolve otherwise ambiguous rows');
const unknown=c.buildShippingManifestProductSummary(c.buildShippingManifestStats([{itemsSummary:'蔗香梨 特別版 24A｜10顆（$999 × 2盒）',totalBoxes:2}]));
assert(unknown.includes('特別版'));assert(unknown.includes('規格待確認'));assert(unknown.includes('10顆'));
assert(c.buildShippingManifestProductSummary(c.buildShippingManifestStats([])).includes('—'));
console.log('PASS shipping manifest: packaging/count/variety/grade identity, equal and changed prices, ambiguous history, separate totals, legacy aliases, empty and unresolved rows');
